version: '3'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: 12345

    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
